cs<-read.table("pollute.txt", header=T)
model<-lm(Pollution~Temp+Industry+Population+Wind+Rain+Wet.days, data=cs)
plot(Pollution~Temp+Industry+Population+Wind+Rain+Wet.days, data=cs)
abline(model)
summary(model)
model1<-lm(Pollution~., data=cs)
step(model1)
null<-lm(Pollution~1, data=cs)
full<-lm(Pollution~., data=cs)
step(null, scope = list(upper=full), data=cs, direction="both")
